import torch
import soundfile as sf
from audioseal import AudioSeal
from torchaudio.transforms import Resample
import sys 
import csv
import datetime
import random 

# --- 1. Load the Model ---
print("Loading AudioSeal generator model...")
try:
    audioseal = AudioSeal.load_generator("audioseal_wm_16bits")
except Exception as e:
    print(f"Error loading model: {e}")
    sys.exit()

# --- 2. Load Audio File ---
input_filename = "my_song.wav" 
output_filename = "watermarked_song.wav"
model_sample_rate = 16000

try:
    wav, sample_rate = sf.read(input_filename)
    print(f"Loaded '{input_filename}', sample rate: {sample_rate}")
except Exception as e:
    print(f"Error loading audio file: {e}")
    print(f"Make sure '{input_filename}' is in the same folder as this script.")
    sys.exit()

if wav.ndim == 2:
    print("Audio is stereo. Converting to mono by averaging channels...")
    wav = wav.mean(axis=1)

wav_tensor = torch.tensor(wav, dtype=torch.float32)
wav_tensor = wav_tensor.reshape(1, 1, -1)

if sample_rate != model_sample_rate:
    print(f"Resampling audio from {sample_rate}Hz to {model_sample_rate}kHz...")
    resampler = Resample(orig_freq=sample_rate, new_freq=model_sample_rate)
    wav_tensor = resampler(wav_tensor)

# --- 3. Define Message ---
print("Generating random ID and metadata...")

ai_models = ['ChatGPT', 'Gemini', 'Perplexity', 'Sora']

# 1. Get the Unique ID 
message_id = random.randint(0, 65535)
message_id_hex = hex(message_id) 

# 2. Get the Metadata 
source = random.choice(ai_models)

# 3. Create the full metadata string
timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
metadata_string = f"Message embedded at {timestamp} to audio generated by {source}"

# 4. Convert ID number to a 16-bit string
bit_string = f'{message_id:016b}' 

# --- Convert the bit string to the tensor format ---
new_bits_list = [int(bit) for bit in bit_string] 
new_bits = [new_bits_list] 
message = torch.tensor(new_bits, dtype=torch.int32)
    
print(f"Embedding ID:{message_id_hex}")

# --- 4. Embed the Watermark ---
print("Embedding watermark...")
watermark = audioseal.get_watermark(wav_tensor, message=message, sample_rate=model_sample_rate)
watermarked_audio = wav_tensor + watermark

# --- 5. Save the New File ---
watermarked_numpy = watermarked_audio.detach().cpu().numpy().squeeze()
sf.write(output_filename, watermarked_numpy, model_sample_rate)

# --- 6. Save Metadata to Log File ---
with open('metadata_log.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow([message_id, metadata_string])

print(f"\nSuccess! Saved '{output_filename}'")
print(f"Metadata saved to 'metadata_log.csv' for ID {message_id}.")
